language: node_js
node_js:
- 11.6.0
cache: npm
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  api_key:
    secure: t+kIHnZskKx1WlYq8dqLaHtKzezSAr838qIt/gCmpfS1IjSUNh4OpjOMfIB6wLRR1VD8RaxZED1H+n9nqGDz6BoVrLgPNkz1rUx5lGcaLTPF3vScMBxlsH/ftMBWgiLmMYN5pDXzdwATfWwRl1NQmqgVnLCX7EdkDzvAtTr/Sc122GOQE9p35YoxwULP8hrcSqXvVDtzc0M6VaSdWev4RaxouX2LWESgwPwHCQQSXpNoT8IovQvTzu6VdddOQNeL7LqRa3KWgIe94f3PPQk5zSitL6sU95KOc8XoZcqRK8Z2IvsGxoxzQPGwuCXH/6+NkBtijgVsVqILIScREe9aAPcBxQgDUu4VkhDdyD+P/69/Zn8YMWpRxTXZfIynnSD+J2fWr3kZ2L3fLG+Ihqgz+NwO08E89qXXQBgwYUARGqWT9OY6AGakCy8JnfB1355uH8pf+BTf71JxEgDOl+G3l2PdyjAVm7OWs7Oq2RpJ2WeVB/nfDxd///JI0yl891uA22W+1/4byOH1lTI0WU8a39ywiTtzdGJIO6ymbXvvkype+6UE//RIrB/3Ix5sgU8+PAFbm4C7Vhd4/lNsOBo8Bg037nZiASWhcr4nE399BjP75gVKS3WNsg7rCDi/nJWuJ5FYTFHnyfWgzYORo80mhTJwNjPkCNniyDR/ky9xMTk=
  app: peppercloud
