language: node_js
node_js:
- 11.6.0
cache: npm
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  api_key:
    secure: $HEROKU_TOKEN
  app: peppercloud
