language: node_js
node_js:
- 11.6.0
cache: npm
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  github-token: 608cff18e30f9fb86d33322e4a20a42f0f3cbc6b
  on:
    branch: master
  api_key:
    secure: E9q4W1S6buZd0FukHO3yDr93F8pjUZZyWSD7soa10q1o2qEySO7ohiksozJsaSQwR+Et+sLqNqzAivtkLdN0XusThomkIVS4IdHnC9+7OvWvuf/75CX9yZ5eDCLaN8yGbRmvWmrnLAT4nu7A2atknf/J2Vzv0cj36aeYFq0Xpyv+0PdC2FHPngIJ64FiHL/ofmI2cJ33V8/rKhgZLQ1eC7mya0lyj7gWaXf3O1YgnkuStp/P15oEEiRPS7KP0/kvmBVBrutMblW+0RsfVU2AtFdp9FlNUibPyzP1aBSNywN6rBwg6slUfNIsp5xLNyqd2eFzvr84GcpXiovyfRBv5koYsbBNqD28fh/ET7GKxnUtEoxplDwa6IBS4PdDAYPbvfnXKtYNyvhl4LLJNAUTIBdzwAEY1YVr3IJnRWUJx7MdfEWQXSKYHadnfh5rvTNcXYulL6DUpJMWA4TfgNAOR79tcr9Z1spZ9TSlrJhoYpbsebSKwGh9nJ2lxLjfOxbLp/ZACNSVttO0PggWVvD1WusUIVasm/rS0s1PbPD/3+4xmuWsUbL1h1N+KbgtHRYUVPyVTDYf2NrXeRPiHj/waBSZsBIlQSuQD1mcV5Blhif3yEH5n9mrR0UtrhRs6DNxs/6vxiOkg6GAXu7pro1CMwBLlGMoEbfPbHk1FIQiQtc=
  app: react-travisci